name: GitHub Snake

on:
  workflow_dispatch:  # permite rodar manualmente
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          # GitHub username para ler o gráfico de contribuições
          github_user_name: BeatrizLorenaCosta

          # lista de arquivos que serão gerados
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa
