name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@v1
        with:
          username: BeatrizLorenaCosta
          output: dist/top-languages.svg
          theme: github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Top Languages
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add dist/top-languages.svg
          git commit -m "Update Top Languages" || echo "No changes to commit"
          git push
