name: Top Languages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # roda todo dia Ã  meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Top Languages
        run: |
          git clone https://github.com/anuraghazra/github-readme-stats.git temp-stats
          cd temp-stats
          npm install
          node index.js --username BeatrizLorenaCosta --output ../dist/top-languages.svg --theme github

      - name: Commit Top Languages
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add dist/top-languages.svg
          git commit -m "Update Top Languages" || echo "No changes to commit"
          git push
